= Simulador: Trabajo Practico 3 - Programación III
:hardbreaks:
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

Autores:Aldana Micaela Filiberto <Aldana.filiberto17@gmail.com>; Juliana Camila Nuñez <julicamila14@gmail.com>;
Docentes: Javier Marenco, Patricia Bagnes (Com-01);
 v1, {docdate}.


== Introducción:

El objetivo del trabajo práctico es implementar una aplicación para realizar simualciones para estimar cuánto dinero en promedio se debe gastar para completar el álbum de figuritas del mundial en distintos escenarios, por medio de técnicas de simulación.
El álbum contiene 638 figuritas y cada paquete tiene 5 figuritas distintas. Suponemos además que la probabilidad de aparición de cada figurita en
cada paquete es la misma, es decir que se imprime la misma cantidad de cada figurita y que las figuritas se reparten con distribución uniforme
entre los paquetes. Una simulación consiste en comenzar con un álbum vacío ygenerar aleatoriamente paquetes de figuritas hasta completar el álbum, 
llevando la cuenta de cuántos paquetes fueron necesarios para terminar el procedimiento. La estimación consiste en realizar un número muy grande
de simulaciones hasta llegar a una estimación (promedio de los paquetes comprados hasta finalizar el proceso) estable.Se pide realizar  simulaciones en los siguientes escenarios:
    1. Un único usuario que busca completar un álbum.
    2. Una cantidad n de usuarios que buscan completar un álbum cada uno. Cuando un  usuario obtiene una figurita repetida (es decir, una 
       figurita  que ya tiene en su álbum), se la dona a otro usuario que la necesite sin obtener nada a cambio. El proceso termina
       cuando todos los usuarios completaron sus álbumes.
    3. Una cantidad n de usuarios que buscan completar un álbum cada uno. Cuando dos usuarios obtienen una figurita repetida cada uno, las 
       pueden intercambiar entre sí. El proceso termina cuando todos los usuarios completaron sus álbumes.

== Desarrollo:
=== Paquetes:
Para la implementación de esta aplicación se crearon los siguientes paquetes:

*escenarios*: Contiene la lógica de cada escenario mencionado.

*interfaz*: Contiene la interfaz gráfica de la aplicación.

*generadores*: Contiene los generadores para generar los paquetes.

*observadores*: Contiene los observadores para la interfaz.

*simuladores*: Contiene las instancias y la logica de la simulación

*test*: Este paquete contiene los test de las clases que están en los paquetes escenario y simuladores.

== Descripcion de las clases de escenarios:
Escenario::  están los métodos que hay que implementar en las clases que van llevar a cabo las siguientes clases:
Escenario1:: 
Escenario2::
Escenario3::
En estas clases contiene la logica para generar un paquete y en donde se pueden cambiar o intercambiar figuritas en el caso de ser posible.
`void generarPaquete(Usuario u, Generador g)` este método genera las figuritas por paquete y las agrega al usuario.

`void simular(Generador g, ArrayList<Usuario> lista)` este método se encarga de que todos los usuarios obtengas paquetes hasta que tengan el albumn completo

== Descripcion de las clases de Generadores:
Generador:: están los métodos que hay que implementar en las clases que van llevar a cabo las siguientes clases:
GeneradorPrefijado::

`int nextInt(int rango)`
`boolean nextBoolean()`
`void setMatrizDePaquetes(int[][] matriz)`
GeneradorRandom::
`int nextInt(int rango)`
`boolean nextBoolean()`

== Descripcion de las clases de Simuladores:
Simulador:: Esta clase se encarga de realizar la simulación.
`void simular()`  se encarga de simular en base al escenario elegido.
`int paquetesGenerados()` se encarga de devolver la cantidad de paquetes que se generaron por simulación.
Instancia:: Esta clase contiene las instancias de datos.
Solucion:: Esta clase hereda la clase Thread
`void ejecutar()`
`void registrarObservador(Observador o)` Registra unobservador a lista.
`void run()`
Usuario:: Esta clase contiene un álbum que es un arreglo de booleanos.
`boolean estaCompleto()` Este método devuelve true en el caso de que el álbum esté completo
`void agregarFigurita(int i)` Este método agrega figuritas al álbum

== Problemas y soluciones:
El primer problema que se nos presentó fue que al querer implementar el escenario2 las figuritas nunca se intercambiaban porque hasta que el primer usuario no terminaba de completar su álbum, el segundo no empezaba a generar figuritas. La solución fue intercalar entre usuarios. 
Otro problema que tuvimos fue el intentar hacer las simulaciones, ya que en primer lugar solo hacia una y la solución fue 
